insert into car ( ID, CONDITION, CREATED_AT, BODY, ENGINE, EXTERNAL_COLOR, FUEL_TYPE, MILEAGE, MODEL, MODEL_YEAR, NUMBER_OF_DOORS, PRODUCTION_YEAR,LAT, LON, MODIFIED_AT, MANUFACTURER_CODE )   VALUES (1,'USED', NULL,'Sedan','Straight Engine','white', 'petrol',19,'Opel Corsa',2000, 4, 2003, 33.3 , 122.2, NULL , NULL);
insert into car ( ID, CONDITION, CREATED_AT, BODY, ENGINE, EXTERNAL_COLOR, FUEL_TYPE, MILEAGE, MODEL, MODEL_YEAR, NUMBER_OF_DOORS, PRODUCTION_YEAR,LAT, LON, MODIFIED_AT, MANUFACTURER_CODE )  VALUES (2,'USED', NULL,'Coupe','Inline Engine','yellow', 'diesel',50,'Citroen C1',2010, 5, 2013, 343.3 , 222.2, NULL, NULL);
insert into car ( ID, CONDITION, CREATED_AT, BODY, ENGINE, EXTERNAL_COLOR, FUEL_TYPE, MILEAGE, MODEL, MODEL_YEAR, NUMBER_OF_DOORS, PRODUCTION_YEAR,LAT, LON, MODIFIED_AT, MANUFACTURER_CODE )  VALUES (3,'USED', NULL,'Wagon','Flat Engine','green', 'hybrid',80,'BMW 3-series',2020, 2, 2020, 353.3 , 322.2, NULL, NULL);
insert into car ( ID, CONDITION, CREATED_AT, BODY, ENGINE, EXTERNAL_COLOR, FUEL_TYPE, MILEAGE, MODEL, MODEL_YEAR, NUMBER_OF_DOORS, PRODUCTION_YEAR,LAT, LON, MODIFIED_AT, MANUFACTURER_CODE )  VALUES (4,'USED', NULL,'Van','Twin Cylinders','red', 'ECV',120,'Audi Q5',2021, 4, 2023, 363.3 , 422.2, NULL, NULL);
insert into car ( ID, CONDITION, CREATED_AT, BODY, ENGINE, EXTERNAL_COLOR, FUEL_TYPE, MILEAGE, MODEL, MODEL_YEAR, NUMBER_OF_DOORS, PRODUCTION_YEAR,LAT, LON, MODIFIED_AT, MANUFACTURER_CODE )  VALUES (5,'NEW', NULL,'Jeep','Twin Cylinders','black', 'ECV',70,'BMW 1-series',2019, 4, 2020, 383.3 , 522.2, NULL, NULL);

insert into manufacturer (CODE,NAME) VALUES (100, 'Audi');
insert into manufacturer (CODE,NAME) VALUES (101, 'Chevrolet');
insert into manufacturer (CODE,NAME) VALUES (102, 'Ford');
insert into manufacturer (CODE,NAME) VALUES (103, 'BMW');
insert into manufacturer (CODE,NAME) VALUES (104, 'Dodge');